# Generated by Django 3.0.6 on 2020-05-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0006_auto_20200520_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qPaperTitle', models.CharField(max_length=100)),
                ('questions', models.ManyToManyField(to='prof.Question_DB')),
            ],
        ),
    ]
