# Generated by Django 3.0.4 on 2020-05-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0007_question_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=10)),
                ('students', models.ManyToManyField(to='prof.Student')),
            ],
        ),
    ]
