# Generated by Django 3.0.4 on 2020-05-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0008_special_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_students',
            name='questions',
            field=models.ManyToManyField(to='prof.Question_DB'),
        ),
    ]
