# Generated by Django 3.0.4 on 2020-05-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0009_special_students_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_students',
            name='question_papers',
            field=models.ManyToManyField(to='prof.Question_Paper'),
        ),
    ]
