# Generated by Django 3.0.6 on 2020-05-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0010_special_students_question_papers'),
    ]

    operations = [
        migrations.CreateModel(
            name='QNO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='question_db',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
