# Generated by Django 3.0.6 on 2020-05-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0011_auto_20200523_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qno',
            name='id',
        ),
        migrations.AddField(
            model_name='qno',
            name='nid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
