# Generated by Django 3.0.6 on 2020-06-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0013_exam_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QNO',
        ),
        migrations.RemoveField(
            model_name='question_db',
            name='number',
        ),
    ]
