# Generated by Django 3.0.5 on 2020-05-28 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0013_exammodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.Question_Paper')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.Special_Students')),
            ],
        ),
        migrations.DeleteModel(
            name='ExamModel',
        ),
    ]
