# Generated by Django 3.0.4 on 2020-05-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.IntegerField(),
        ),
    ]
