# Generated by Django 3.0.4 on 2020-05-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_auto_20200519_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
