# Generated by Django 3.0.6 on 2020-05-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0005_question_db_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_db',
            name='id',
        ),
        migrations.AddField(
            model_name='question_db',
            name='qno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
