# Generated by Django 3.0.5 on 2020-06-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0014_auto_20200606_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_paper',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='special_students',
            name='question_papers',
        ),
        migrations.RemoveField(
            model_name='special_students',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='special_students',
            name='students',
        ),
        migrations.DeleteModel(
            name='Exam_Model',
        ),
        migrations.DeleteModel(
            name='Question_DB',
        ),
        migrations.DeleteModel(
            name='Question_Paper',
        ),
        migrations.DeleteModel(
            name='Special_Students',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
