# Generated by Django 3.0.5 on 2020-06-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200607_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
