# Generated by Django 3.0.5 on 2020-06-07 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special_students',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'Student'}, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
