# Generated by Django 3.0.5 on 2020-06-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200607_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_model',
            name='student_group',
        ),
        migrations.AddField(
            model_name='exam_model',
            name='student_group',
            field=models.ManyToManyField(to='main.Special_Students'),
        ),
    ]
