# Generated by Django 3.0.6 on 2020-06-09 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_remove_special_students_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_db',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Professor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
