# Generated by Django 3.0.5 on 2020-06-12 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200609_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 10, 1, 13, 569529, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
