# Generated by Django 3.0.5 on 2020-06-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_exam_model_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(verbose_name=['%Y-%m-%d %H:%M']),
        ),
    ]
