# Generated by Django 3.0.5 on 2020-06-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200612_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
