# Generated by Django 3.0.5 on 2020-06-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200612_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='question_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='main.Question_Paper'),
        ),
    ]
