# Generated by Django 3.0.5 on 2020-06-17 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200615_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
