# Generated by Django 3.1 on 2020-08-22 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_exam_model_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_model',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='exam_model',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='special_students',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'Stud'}, related_name='group', to=settings.AUTH_USER_MODEL),
        ),
    ]
