# Generated by Django 3.1 on 2020-08-23 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200823_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 16, 36, 22, 426651)),
        ),
        migrations.AddField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 16, 36, 22, 426651)),
        ),
    ]
