# Generated by Django 3.0.6 on 2020-06-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0007_remove_special_students_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu_Question',
            fields=[
                ('question_db_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Question_DB')),
                ('choice', models.CharField(max_length=3)),
            ],
            bases=('main.question_db',),
        ),
    ]
