# Generated by Django 3.0.6 on 2020-06-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_stu_question_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_question',
            name='student',
        ),
    ]
