# Generated by Django 3.0.6 on 2020-06-09 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0005_auto_20200609_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_question',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
