# Generated by Django 3.0.6 on 2020-06-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200609_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_question',
            name='choice',
            field=models.CharField(blank=True, default='E', max_length=3, null=True),
        ),
    ]
