# Generated by Django 3.0.6 on 2020-06-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_exam_db_results_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_db',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
