# Generated by Django 3.0.6 on 2020-06-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20200611_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuexam_db',
            name='questions',
            field=models.ManyToManyField(blank=True, to='student.Stu_Question'),
        ),
    ]
